name: Kudos
version: '${project.version}'
main: de.urbance.Main
api-version: 1.19
authors: [ Urbance ]
website: https://github.com/Urbance
softdepend: [PlaceholderAPI]
commands:
  kudos:
    description: Opens GUI or shows Kudos from a player
  kudo:
    description: Award someone a Kudo
  kudmin:
    description: Administrator tools
permissions:
  kudos.gui:
    description: Allows to open the GUI
  kudos.show:
    description: Allows viewing of Kudos from other players and itself
  kudos.*:
    description: Allows all kudos user commands
  kudos.award:
    description: Allows the awarding of Kudos
  kudmin:
    description: Allows to execute administrator commands